#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <math.h>

#define MAX_BUFFER_SIZE 256
#define NUM_BOUNDING_BOX_VERTEX 8
#define NUM_TRIANGLE_VERTEX 3
#define MAX_TRIANLGE_COUNT_PER_MODEL 5000000
#define NO_ATTRIBUTE -100

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define FIELD_OF_VIEW 90
#define NEAR_FRUSTUM 0.1f
#define FAR_FRUSTUM 1000

#define NUM_FRUSTUM_PLANES 6

#define NEGATIVE_OF_PLANE -1
#define ON_PLANE 0
#define POSITIVE_OF_PLANE 1

#define INSIDE_FRUSTUM 1
#define INTERSECT_FRUSTUM 0
#define OUTSIDE_FRUSTUM -1

#define NORMAL_VECTOR_LENGTH 20.f

#define MOVEMENT_SPEED_MULTIPLIER .1f
#define TURNING_SPEED_DEG 1
#define TURNING_SPEED_RAD 1.0f / 180.0f

#define NS_TO_SEC_INT 1000000000
#define NS_TO_SEC_FLOAT 1000000000.0f

#define DEGREES_TO_RADIANS M_PI / 180
#define RADIANS_TO_DEGREES 180 / M_PI

#endif
